export const ADD_COUPONS = 'ADD_COUPONS';
export const ADD_PRODUCT_ITEMS = 'ADD_PRODUCT_ITEMS';
export const ADD_SHOPPING_BAG = 'ADD_SHOPPING_BAG';
export const SET_USER = 'SET_USER';
export const ADD_SHOPPING_CART = 'ADD_SHOPPING_CART';
export const REMOVE_SHOPPING_CART = 'REMOVE_SHOPPING_CART';